name: NexoriaDatabase
version: '1.0.0'
main: dev.nexoria.database.NexoriaDatabasePlugin
api-version: '1.21'
folia-supported: true
author: NexoriaStudio
description: "Asynchronous connection pool manager supporting SQLite, MySQL, MariaDB, and MongoDB."
website: https://modrinth.com/plugin/nexoria-database

commands:
  database:
    description: Primary command entrypoint for NexoriaDatabase
    permission: nexoria.database.use
    aliases: [database]

permissions:
  nexoria.database.admin:
    description: Full administration privileges for NexoriaDatabase
    default: op
  nexoria.database.use:
    description: Standard player privileges for NexoriaDatabase
    default: true
