name: NexoriaCustomItems
version: '1.0.0'
main: dev.nexoria.customitems.NexoriaCustomItemsPlugin
api-version: '1.21'
folia-supported: true
author: NexoriaStudio
description: "Framework for building custom weapons, tools, and abilities with cooldowns and mana costs."
website: https://modrinth.com/plugin/nexoria-customitems

commands:
  customitem:
    description: Primary command entrypoint for NexoriaCustomItems
    permission: nexoria.customitems.use
    aliases: [customitems]

permissions:
  nexoria.customitems.admin:
    description: Full administration privileges for NexoriaCustomItems
    default: op
  nexoria.customitems.use:
    description: Standard player privileges for NexoriaCustomItems
    default: true
