name: NexoriaNBT
version: '1.0.0'
main: dev.nexoria.nbt.NexoriaNBTPlugin
api-version: '1.21'
folia-supported: true
author: NexoriaStudio
description: "Type-safe PersistentDataContainer (PDC) wrapper and custom item metadata API."
website: https://modrinth.com/plugin/nexoria-nbt

commands:
  nbt:
    description: Primary command entrypoint for NexoriaNBT
    permission: nexoria.nbt.use
    aliases: [nbt]

permissions:
  nexoria.nbt.admin:
    description: Full administration privileges for NexoriaNBT
    default: op
  nexoria.nbt.use:
    description: Standard player privileges for NexoriaNBT
    default: true
