name: NexoriaSpawners
version: '1.0.0'
main: dev.nexoria.spawners.NexoriaSpawnersPlugin
api-version: '1.21'
folia-supported: true
author: NexoriaStudio
description: "Stackable mob spawners and smart AI throttler to maximize server FPS and performance."
website: https://modrinth.com/plugin/nexoria-spawners

commands:
  spawners:
    description: Primary command entrypoint for NexoriaSpawners
    permission: nexoria.spawners.use
    aliases: [spawners]

permissions:
  nexoria.spawners.admin:
    description: Full administration privileges for NexoriaSpawners
    default: op
  nexoria.spawners.use:
    description: Standard player privileges for NexoriaSpawners
    default: true
