name: NexoriaPunish
version: '1.0.0'
main: dev.nexoria.punish.NexoriaPunishPlugin
api-version: '1.21'
folia-supported: true
author: NexoriaStudio
description: "Moderation suite featuring bans, mutes, warnings, IP blacklists, and Discord security alerts."
website: https://modrinth.com/plugin/nexoria-punish

commands:
  punish:
    description: Primary command entrypoint for NexoriaPunish
    permission: nexoria.punish.use
    aliases: [punish]

permissions:
  nexoria.punish.admin:
    description: Full administration privileges for NexoriaPunish
    default: op
  nexoria.punish.use:
    description: Standard player privileges for NexoriaPunish
    default: true
